// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shfsvdvijfobhcaoiyfo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNoZnN2ZHZpamZvYmhjYW9peWZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NDkwNjYsImV4cCI6MjA3MDIyNTA2Nn0.nchQVvvmREWXsVlkrmoUG1C_vkh8F_6IwZP80qCoRSM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});